apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-db
spec:
  destination:
    namespace: azure-native
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/db/azure-native
    repoURL: https://github.com/gestrem/dora-demo-rh
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true