# gitops filder

# create placement objects if not created
oc create -f gitops/placements/apps-placement.yaml
oc create -f gitops/placements/location-placement.yaml


# create hub-apis sa and generate token with cluster-admin role
oc create sa hub-apis
# create token valid for 10days
oc create token hub-apis --duration 14400m
# a secret will be created with the token that can be used fot he API calls (hub-apis-token-XXXXX)
oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:hub-ns:hub-apis
# curl -k -H "Authorization: Bearer TOKEN" "https://api.cluster-sql9s.sql9s.[Base DNS Domain]:6443/apis/policy.open-cluster-management.io/v1/namespaces/openshift-gitops/policies/hub-ns"


# create hub-apis-token secret
cat <<EOF | oc apply -f -
kind: Secret
apiVersion: v1
metadata:
  name: hub-apis-token
  namespace: hub-ns
data:
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrdDFOVFE0TFZOMFJEZGFlRXR2WTNSeGFURjNSMnRGY1VrMlFXMUxjR0k1UTNVMFkweGpSbTEyU3pnaWZRLmV5SmhkV1FpT2xzaWFIUjBjSE02THk5cmRXSmxjbTVsZEdWekxtUmxabUYxYkhRdWMzWmpJbDBzSW1WNGNDSTZNVGMwTURZMk5UVTBOaXdpYVdGMElqb3hOek01T0RBeE5UUTJMQ0pwYzNNaU9pSm9kSFJ3Y3pvdkwydDFZbVZ5Ym1WMFpYTXVaR1ZtWVhWc2RDNXpkbU1pTENKcWRHa2lPaUpqTVRZeE5tSmhNQzAwT0RnMkxUUXhabUV0T0RBeU1DMDNabVUwT1RKak9XTTRZMllpTENKcmRXSmxjbTVsZEdWekxtbHZJanA3SW01aGJXVnpjR0ZqWlNJNkltaDFZaTF1Y3lJc0luTmxjblpwWTJWaFkyTnZkVzUwSWpwN0ltNWhiV1VpT2lKb2RXSXRZWEJwY3lJc0luVnBaQ0k2SWpJd016RXhNVE0yTFRrMFptSXROR0k1WkMwNU5HSmpMVGswWkdZd1pEVXhZak0wTWlKOWZTd2libUptSWpveE56TTVPREF4TlRRMkxDSnpkV0lpT2lKemVYTjBaVzA2YzJWeWRtbGpaV0ZqWTI5MWJuUTZhSFZpTFc1ek9taDFZaTFoY0dsekluMC5tTlQxdHZsWTNUZHY4am94eXM0UktwUGhBNXkzZDdNanFnX0FPa3dXOVU3cFFZZXF3c1lwcmlfaEFIQ245eGhPZWkxbUp3SDNsaWNpbEVvMEV0OWRKR1BWVHAtUDFmQ1dqLV9XSk0tejF5eXJlSmtzbl83dnU3anp1MExjZmQzeWp3ZmNXaTg3MVVEejlqd2E2bC1lUWZYMmxXaEVtb013OGdiRXVPTzBzWEpYMnNOeVRsUjdiVXJmTF91MHpmOVdJM2k2Z29meHBwQkktRVhWbXRJLS1WOE43bG1fNUlPbnN5a0dqbVBxeTVIalVSM2dqQWVoUVpWTHZLWFI4enZ3ZXE2MzZvLWZnZG9YQlloaXhIclkxOG1EU2VYTHZKMXRaNW5mUDE4N1J6VVNQd2dRM0MtZmV1V3l4WldUNzVSRGNMOVVSZDNOLU9ocUtzbjhjX3p1d192OG5rR09hc1VTTml6RFFudU0tZWJTYnBUQlg4UXpxaEpmdzk0UXV3OWEtbW5Xc0RILWhpd3pXUTZETUxNZlFESVZOanZEMHBNeUdVSWtIcjNkRlVtT2FSZ0xFUHdMMjl4bW1faVFEOHRpaGRnbmV5Ykw3SDBveWhfZEp3bXVmdm4yRnlGemt2MDQ5cjlHZjlPRUpKaUlnN3lHTFdwa1lhbGY3cGFPbjhycjRXQVZQZTVVeEMxQkpWLXV0QnhEM0NHUDhfS1laaE1IV2Y3WTRLbGs5M0kxcTRoN3pjcXZXMWZjb0xSWWJvVnNiMk9ERjlETWhQMTdOdG96R2cycWExU0NWVDktMVBJUXFLa3gwUGh6ZWxvNXRhMXBzbHNhN0txcTNSdjJES2ZqR1Y5ZzRfYUNDTGhQc1htVVVsdTA2aFdIX2I4STQ1Ry1QNDlTb2JGdDAwNA==
type: Opaque
EOF

oc create -f gitops/placements/argocd-placement.yaml


# once secret is created, then deploy the dashboard app
# deploy dashboard app
oc create -f gitops/dashboard-applicationset.yaml -n openshift-gitops



# delete 
#oc delete  -f gitops/dashboard-applicationset.yaml -n openshift-gitops

