apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db-config.yaml
- db.yaml
- db-job.yaml
# delete service when you enable RHSI because it's replaced by skupper service
# - db-service.yaml